function_template:
  name: function name
  about: Create a new function in application
  title: [Function]
  labels: [exist, unexist]
  assignness: "@Prcnsi"

description:
  purpose: ""
  detail: ""

core_code: |
  def helloworld():
    print("oss-ai lecture")

edit_location: 
  - Main page: false
  - Event Page: false
  - PopUp page: false
  - Apendix page: false

category: 
  - Add function: true
  - Delete function: false
  - Modify function: false
  - Apendix page: false

additional_context: "Add any other context about the problem here."
