name: "Add function template"
description: :fire:**Write modified core code**:fire: @Prcnsi
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Edit location
      options:
        - Main page 
        - Event Page
        - PopUp page
        - Apendix page
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: category
      multiple: true
      options:
     - Add function
     - Delete function
     - Modify function
     - Apendix page
  - type: textarea
    id: what-happened
    attributes:
      label: Write modified core code
      description: description
      placeholder: Tell us what you see!
      value: "Tell us what you think"
    validations:
      required: true
